Server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_sber_database
    username: root
    password: EgorWar05War
  jpa:
    show-sql: false
    hibernate.ddl-auto: none
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
    enabled: true
    drop-first: true